### PR TITLE
Refresh Icon

### PR DESCRIPTION
**Pull request by res2k**
Hi,
I think the icon could be improved in a couple of ways:
* It's a white outline on a yellow background. This makes for poor contrast.
* The speech bubble shape makes it look a bit like an instant messaging app.
* The icon is not adaptive.
I tried to address these issues by adding a sort of drop shadow, toning down the speech bubble, and making the whole thing adaptive.

Basis for the changes was the previous icon, traced in Inkscape. The SVGs I used are included as well.

### CODE REVIEW

**Comment by moshpirit** [comment]
LOL I've just seen this haha I've just created my own version xD #33 
I must say I still prefer my version though.

>The speech bubble shape makes it look a bit like an instant messaging app.

I can agree with you but it's about debating so I think it makes sense there's this bubble. Maybe we could add some clock marks, this way it's more related to timing and less about the conversation itself. 

>The icon is not adaptive.

What do you mean?

**Comment by res2k** [comment]
Adaptive icons - see:
https://medium.com/google-design/understanding-android-adaptive-icons-cee8a9de93e2
https://medium.com/google-design/designing-adaptive-icons-515af294c783
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by moshpirit** [comment]
I see thanks!! I have no idea about how to code the masks/layers thing, I only know about Inkscape :\ (I do know how to use Inkscape layers though). So, I made this other version, maybe you might like it more than the other I made:

**Comment by res2k** [comment]
What's necessary is to produce an image for the background and an image for the foreground layer (so, two images in total). For your last icon that could be a solid dark blue area for the background image and the half-alarm/half-human as the foreground image on a transparent background.
The layering & masking of these images will be handled by Android.

**Comment by moshpirit** [comment]
Cool! Then here's the [SVG file](https://my.owndrive.com/index.php/s/MnrD3vcCePi9Zgg) I differenciated the layers

**Comment by czlee** [comment]
Thanks to both of you! Just wanted to say I've seen this and I really appreciate it but owing to other debating software (and other) commitments it'll be a while before I get to look at this—will look to do so during (Northern Hemisphere) summer. 🙂

**Comment by czlee** [comment]
Just wanted to give an update (not good news unfortunately) that I didn't manage to get to this during summer and I'll now be flat out with WUDC prep until WUDC, which makes my next opportunity to look at this in January. Sorry! But thanks again for doing this!

**Comment by Zankoas** [comment]
@czlee Any news about when you'll be able to update your wonderful app?

**Comment by czlee** [comment]
No, sorry 😔 I'm actually in France as a visiting student researcher for the summer, so don't anticipate getting time soon. But since I'm not going to WUDC this year (let alone helping it run it), I think I'll aim to make time for it when I'm home for winter (Christmas) break this year?

**Comment by moshpirit** [comment]
Tbh I didn't know changing the icon that time consuming, how much time does it take? (I can wait until Christmas, I'm just curious)

**Comment by Zankoas** [comment]
That would be amazing, thanks

**Comment by czlee** [comment]
It's more that I need to download, install and set up a new development environment, and then bring everything in Debatekeeper up to date with current Android stuff before I can even start working on the app! It really has been that long since I've last touched this app—I got a new computer since then, and even that was a couple of years ago. All my debating software time's been sunk into [Tabbycat](https://github.com/TabbycatDebate/tabbycat/), and even that's been lagging since WUDC.

**Comment by czlee** [comment]
After three years (or five since the last update), I've got my development environment up and brought Debatekeeper up to API level 29, and this is next on my to-do list! I'll see what I can do with it in the next couple of days.

**Comment by czlee** [comment]
I feel very grateful to have two logos submitted here! Thanks in particular for the discussion above re adaptive icons. Like @moshpirit I can only do basic Inkscape stuff, but thanks to @res2k's guidance I was able to figure out Android's Image Asset Studio and get it to work. Here are screengrabs of both when installed:

mockup-res2k mockup-moshpirit

Graphic design isn't really my thing, as you might've noticed. If you think the current logo is primitive—it was a quick favour from a friend—you should see the original placeholder:



Anyway, like I say, very grateful to have both of you in here. If either of you have thoughts on which to take, other than the natural preference for your own, they'd be very useful to hear. But I'm canvassing opinions from a few friends and I'll put one of them in soon 😊

**Comment by res2k** [comment]
@czlee TBH I think @moshpirit's one looks better. It's certainly more contrast-y, and I'm not sure if the bell design I opted for is easily recognized as such.
And I think it looks quite nice on the screengrab... so perhaps just go for it :)

**Comment by czlee** [comment]
Merged @moshpirit's in b9d19e666d6d7beb85c383ec83df88bf53d9a1cb, thanks again!

**Pull request closed without merging**
