### PR TITLE
Add Middle School Public Debate Program (MSPDP) format 

### PR DESCRIPTION
**Pull request by pmcheng**
This is a common debate format for the middle school level in the United States.

Debate format source: http://www.middleschooldebate.com/s/MSPDP-Rules-2015.pdf

### CODE REVIEW

**Comment by czlee** [comment]
Thanks! Did you want to include the 20-minute prep time in the format?

**Comment by pmcheng** [comment]
Thanks for making this project!  I personally don't think I need the prep timer, prep timing doesn't seem to be very strict at this level.

**Comment by Revenar** [comment]
I was actually looking for this format myself, as we have a few MSPDP tournaments coming up in the local area.  I would recommend adding the prep timer though, as some leagues are more strict than others when it comes to starting rounds on time.

**Comment by pmcheng** [comment]
Ok, I added the 20 minute prep timer, it's easy enough to swipe past it if you don't use it.

**Comment by czlee** [comment]
Thanks @pmcheng! Also, for reference, you can actually disable the prep timer completely (for all formats), it's under Settings :wink:

In terms of merging—obviously I'm happy to merge, but it's easiest for me to put it into the beta version, which is (at the moment) quite different from the production version. You (and anyone else) can get the beta version by signing up here: 
https://play.google.com/apps/testing/net.czlee.debatekeeper

Would that work okay? If enough people would use it immediately, I can put it in the production version, it'd just require some Git and version numbering trickery.

**Comment by pmcheng** [comment]
Feel free to do what seems best, beta version is fine with me.  Thanks also for pointing out the option to hide the prep timer, I hadn't noticed that.

**Comment by czlee** [comment]
Just a heads-up, I'm renaming the file to "mspdp.xml" and the display name to "Middle School Public Debate Program" to disambiguate it a little, since I assume there are also other styles of debate practiced by middle school students in the United States (even if they're not currently supported by Debatekeeper). Let me know if the original name ("Middle School Debate") should stand. The length of the name doesn't bother me (at least not with the UI changes in the beta version).

**Comment by pmcheng** [comment]
Sounds good, thanks.

**Pull request merged**
