### PR TITLE
Greek and BP 6-minute speeches

### PR DESCRIPTION
**Pull request by geoangelotti**
Xmls for 6-minute speeches Australs and BP debating formats.

### CODE REVIEW

**Comment by czlee** [comment]
Looks good! Though, the 6-minute Australs format looks like it's 2 vs 2 with POIs, which is a bit different from the Australasian Championships, which is 3 vs 3 without POIs. Does your circuit call it Australs anyway? Could we call it something more specific?

**Comment by geoangelotti** [comment]
We call it in Greek "Διττοί Λόγοι" that could be translated "Twofold Reasoning" or "Dual Speeches" (sounds horrific) but if it is like Australasian Championships i believe that it is unnecessary.

**Comment by czlee** [comment]
It's not really like the Australasian Championships at all—I consider both 3 vs 3 and the absence of POIs to be defining features of the Australs format. So I'd rather call it some translated version of the name (even if it's just "Greek 2 vs 2"), or if the debate format is practised in Greek (as below), just have the entire file in Greek.

In fact, is this format practised in Greek or in English (or both)? I'm working on translated versions of Debatekeeper (to match the language of the user's phone), if you or anyone you know would be interested in helping with that?

Thanks again for submitting these formats!

**Comment by geoangelotti** [comment]
The format is practised only in Greek to the best of my knowledge and is a mix of Australs but with pois in the substantive speeches.
Yes we can name it Greek 3v3.
I would be glad to help you.

**Comment by czlee** [comment]
Ah, it's 3 vs 3—there are only two substantive speeches in the file, so does a different person give the reply speech, to each of the substantive speeches? (Context: in Australs, the reply speaker must be the same person as the first or second of the three substantive speakers.)

**Comment by geoangelotti** [comment]
Yes it is 3v3 with 2 substantive speeches and 1 reply (all of them performed by different speaker).

**Comment by czlee** [comment]
Hi! Just a note to say that I think I'm finally getting some time to attend to Debatekeeper, and I plan to include this (and other debate formats people have submitted in the last few years) in the next release in couple of weeks, after I'm done with some refactoring. I'm just letting you know in case anything's changed about this format since you submitted it, so there's an opportunity to modify it if necessary. Thanks, and sorry about the delay!

**Comment by geoangelotti** [comment]
Hello.
You can include them, they don't need any changes.

**Comment by czlee** [comment]
Hi! A further update on my previous message. Since actual app updates have been too unreliable, I've decided to move debate formats to an [online repository](https://github.com/czlee/debatekeeper-formats). Starting from the next version of Debatekeeper, to be released in the next month or so, Debatekeeper will allow users to download formats from this repository (from within the app). Most debate formats will no longer be distributed with the app itself.

I wanted to invite you to resubmit your format to the new repository at https://github.com/czlee/debatekeeper-formats. I can just copy the file over if you prefer, but I just thought it would be proper for you to get credit for the commit in that repo.

Since it's an online repository, after the Debatekeeper update goes out on Google Play, it'll become available to users (who have updated the app) as soon as it's merged into the new repository. So there's no strict deadline—it doesn't have to get in before app release—but if I haven't heard anything a few weeks after the update is released (probably around late October 2021), I'll go ahead and copy the file to the new repository myself.

Thanks again for submitting this pull request!

**Comment by czlee** [comment]
Merged into new online repository as czlee/debatekeeper-formats#1.

**Pull request closed without merging**
