### PR TITLE
Add German translation and support for multilingual formats

### PR DESCRIPTION
**Pull request by res2k**
This branch contains both a straight-up translation of strings to German as well as a facility to specify 'multilingual' debate format files.

### CODE REVIEW

**Comment by czlee** [comment]
Oh this looks amazing, thanks so much! Not sure if you saw, but I had started translations in the [translations branch](https://github.com/czlee/debatekeeper/tree/translations). There's no logic in that branch though, just translation files, so the merge should be okay.

But I notice you've provided an answer to one question that's been plaguing me: Should the language of the speaker position names follow the format, or the phone? So if your phone is in German (because _e.g._ you are German) but you're at an English-speaking BP tournament (say, WUDC), is it better for "Prime Minister" to show in English or German? Originally I was just going to take a hard line and say that it should follow the format, so _e.g._ OPD speaker position names would show in German on everyone's phone, and "British Parliamentary" and "Parlamento Británico" would be listed as distinct formats. I thought this partly because many formats are only practised in one language, and partly because it was easier to implement (it wouldn't have required any logic). But since you went the other way, I'd be fascinated to hear your thoughts?

I don't have Android Studio on my new computer and am tied up with Tabbycat work so it'll be a while before I get a chance to try this out, apologies in advance!

**Comment by res2k** [comment]
Hmm, that's a tricky question...

Language-following-format is certainly fine for formats that are predominantly used in one region - OPD, for example, is probably rarely used outside German-speaking regions. Still, I think providing an English might have some value, perhaps for non-native speakers in Germany, or just for the odd adventurous non-German speakers wanting to try it out.
On the other hand, worldwide formats like BP are used in various languages; from my (limited, TBH) experience, German-language BP debates tend to use the German terms, and I guess this is similar in other languages - so offering a choice between multiple languages definitely makes sense here.

The "how" of the choice is also an interesting matter. Going for "phone" preferences was an easy way to get a personal user preference, but it's quite possible this isn't always what the user wants - taking your example of an international tournament, a user may prefer the English terms while there, but use his native terms when back home.
So maybe some middle ground would be to allow an explicit language selection. Adding distinct formats for every language would clutter up the format selection pretty quickly.
But perhaps a separate dropdown or something to allow the user to choose any language provided by the format would be a good solution. Or a general preference to choose between "translated" and "format-native" terms - probably simpler to realize at a slight loss of flexibility.

Apart from the speaker names (and other speech-relevant terms) formats also have metadata like name, description etc. - I think those are actually most useful if generally displayed in the user's preferred language.

**Comment by czlee** [comment]
Hello! I've started looking at this, finally. Sorry about the delay, and thanks for your, umm, patience 😅. I've merged the current `master` branch into this, and then this into the `translations` branch. If you're interested, you're welcome to merge this into `translations`.

Notes:

1. I've bumped the schema version supporting translations to "2.3", since I'm currently using 2.2 to add a version number in the [new online formats repo](https://github.com/czlee/debatekeeper-formats). But if this goes in the next update, I'll either define schema 2.2 to include language support (and the new version number), or I'll bump to 3.0 if it's backwards-incompatible (as it currently is).

2. OPD won't be in the assets in the next update; it's being moved (along with most others) to the online formats repo. This isn't a big deal, just noting here so it's clear where it'll go.

Questions:

3. I'd prefer for `DebateFormatFieldExtractor` (previously `DebateFormatStyleNameExtractor`) to quit as soon as it's found what it needs. But I see why translations makes this a bit trickier. Will think about a way to do this. Might involve a schema change—maybe using the `<text lang="de">...</text>` pattern in all multilingual fields, so e.g.

    ``` xml
    <name>
      <text lang="en">Open Parliamentary</text>
      <text lang="de">Offene Parlamentarische Debatte</text>
    </name>
    ```

    That way there's still only one element the extractor needs to find before it parachutes out. Another way is to require that all the `<name>` tags (for example) be together (as they are in the new opd.xml file). Thoughts welcome?

4. If the user's language isn't supported by the format, how does it choose what language to show? Should format files designate a "format-native" (or "primary" or whatever) language for the format, that it falls back to?

5. One thing I'd like is for this not to increase the overhead in writing a format file for a monolingual format. Ideally the old XML schema, not specifying anything about languages, would continue to be valid in the new schema. (But some small changes to the schema are also okay—it's more about clutter than backwards compatibility.) I think in the PR as currently formed, this ends up being true for all elements except the ones using the `<text lang="de">...</text>` pattern, right? (So this conflicts with my idea in point (3) above 😂.)

Thanks again for your work on this! I'll totally appreciate if your priorities have changed since you submitted the PR (much like mine did, haha), but thought I should drop a note about my current thinking as I look to include this in the next update.

**Comment by res2k** [comment]
Hi again,
> 1. I've bumped the schema version supporting translations to "2.3", since I'm currently using 2.2 to add a version number in the [new online formats repo](https://github.com/czlee/debatekeeper-formats). But if this goes in the next update, I'll either define schema 2.2 to include language support (and the new version number), or I'll bump to 3.0 if it's backwards-incompatible (as it currently is).

Well, the exact version doesn't really matter anyway.
The main reason for the version bump was to ensure a format with translations wouldn't be readable on an older DK version (where it most certainly wouldn't be useable).

> 2. OPD won't be in the assets in the next update; it's being moved (along with most others) to the online formats repo. This isn't a big deal, just noting here so it's clear where it'll go.

I'll try to get an update there once an updated translation support should be available.

> 1. I'd prefer for `DebateFormatFieldExtractor` (previously `DebateFormatStyleNameExtractor`) to quit as soon as it's found what it needs. But I see why translations makes this a bit trickier. Will think about a way to do this. Might involve a schema change—maybe using the `<text lang="de">...</text>` pattern in all multilingual fields, so e.g.
>    ```
>    <name>
>      <text lang="en">Open Parliamentary</text>
>      <text lang="de">Offene Parlamentarische Debatte</text>
>    </name>
>    ```
>          
>    That way there's still only one element the extractor needs to find before it parachutes out. Another way is to require that all the `<name>` tags (for example) be together (as they are in the new opd.xml file). Thoughts welcome?
> 2. [...]
> 3. One thing I'd like is for this not to increase the overhead in writing a format file for a monolingual format. Ideally the old XML schema, not specifying anything about languages, would continue to be valid in the new schema. (But some small changes to the schema are also okay—it's more about clutter than backwards compatibility.) I think in the PR as currently formed, this ends up being true for all elements except the ones using the `<text lang="de">...</text>` pattern, right? (So this conflicts with my idea in point (3) above 😂.)

Point 1 and 3 relate to another so I'll just lump my answers together 🙃

While I'm not _exactly_ sure what my thinking was back then, it looks like I went for the `<name lang="XX">...<name lang="YY">...` (let's call it "unnested") pattern when the schema requires exactly one element of a type, and I went for the `<element><text lang="XX">...<text lang="YY">...</element>` ("nested") pattern when multiple `<element>`s can occur.

In general, I think the "unnested" approach seems easier for format authors. Easier to parse for humans. There's little to none overhead when creating monolingual formats. Extending an existing monolingual format with translations is a straightforward process.

However, the current approach is a mix of "nested" and "unnested". The downside is inconsistency. The author must know which elements are "unnested" and which require nested `<text>` elements; it may not be something you can glean from a monolingual format. It's also requires multiple approaches in the parser implementation.

Compared to that, using the "nested" pattern everywhere may be more consistent and easier to parse programmatically, but is probably more cumbersome to write.

One idea might be a hybrid approach: make it "okay" to write a, say, "unnested" `<region>` element, in which case the language is assumed to be the "format-native" language; but also check for nested `<text>` elements and parse them if present. Upside: Monolingual formats stay compact. Downside: Conversion to multilingual adds possibly non-obvious complexity.

Another idea: use different nesting. It seems the only tags that currently use `<text>` tags are some beyond `<info>`. Perhaps it makes sense to use an entirely different structure here, such as:
```xml
<regions lang="en">
  <region>Germany</region>
</regions>
<regions lang="de">
  <region>Deutschland<region>
</regions>
<levels lang="en">
  <level>University</level>
</levels>
<levels lang="de">
  <level>Universität</level>
</levels>
<used-ats lang="en">
  <used-at>German-Language Championship</used-at>
</used-ats>
<used-ats lang="de">
  <used-at>Deutschsprachige Meisterschaften</used-at>
</used-ats>
```

Yet another idea: Just stick the `lang` attibute on the `<info>` tag and allow multiple of those.
(This may actually be the simplest of all the ideas here. The main downside I see is that multiple translations for the same string are apart in the file, possibly causing authors to more easily lose "sync" between them - i.e. `<info lang="en">` suddenly has different regions than `<info lang="de">`.)

Now all this musing about formats doesn't answer your question about `DebateFormatFieldExtractor`.
I think personally I'd try to prefer a format that is friendly to the author; in the case of e.g. `<name>` tags, that would be the "unnested" approach, so it would require `DebateFormatFieldExtractor` to look for multiple elements.
Requiring certain elements to be next to be one another seems like a sensible requirement, even it's isn't quite XML-ish.
But also consider you could deal with this through some format "preprocessing": I see a "validate.py" in the formats repo. This could also check/warn when certain tag, such as `<name>`, are not adjacent to each other.

Last but not least, one could perhaps argue that it's fine to have `DebateFormatFieldExtractor` just "scan the whole format file" - the format file sizes are in the kilobytes range, so the additional effort resulting from processing more than what's strictly necessary may not actually matter that much.

> 2. If the user's language isn't supported by the format, how does it choose what language to show? Should format files designate a "format-native" (or "primary" or whatever) language for the format, that it falls back to?

Designating such a language sounds sensible. Quite a number of formats have a "mother tongue" anyway. Seems like a natural fit for the `<info>` block.

> Thanks again for your work on this! I'll totally appreciate if your priorities have changed since you submitted the PR (much like mine did, haha), but thought I should drop a note about my current thinking as I look to include this in the next update.

I may or may not get around to write some Java again, but in any case, I'm happy to add my two (or more) cents to any discussions 😜

**Comment by czlee** [comment]
I looked up if there's some sort of existing "best practice" for multilingual XML documents, and much to my chagrin I found (https://www.w3.org/TR/xml-i18n-bp/#DevMLDoc):
> ### Best Practice 12: Working with multilingual documents
>
> Avoid document formats that store multiple localized versions of content within the same document.
>
> **How to do this**
>
> For documents that need to go through some localization tasks, always store the localized version of the text in a separate document.
> 
> **Why do this**
> 
> There are two main reasons to avoid sending documents for localization if the source material is located in parallel with the different translations in the same document:
> 
> 1. It is difficult to manage concurrent translations in all languages. It is very likely that each translation will be done by a different translator, in a different location. To facilitate this, the document will have to be broken down into separate parts and reconstructed later on. This adds processing time, increases cost and provides more opportunities for the introduction of errors.
> 
> 2. Depending on the point in the document's lifecycle, such a document may already contain translations, some up-to-date and some outdated (because the source material may have changed). In order to identify what parts need to be localized and what parts should be left alone, the document would then also need to contain custom information about localization state, which may or may not be supported by localization tools.

I think we have good reason to consider the reasons offered there not to apply to our case—format files are short and will probably often be "localized" by their authors. Well, at least that's true if we expect most formats to be published only in their native language and maybe one or two others. I suppose I could imagine a system where debate formats are localized like how most software is, but… there's a Pandora's box opened once we go there.

-----------------

Back to the main question:

> Yet another idea: Just stick the `lang` attibute on the `<info>` tag and allow multiple of those. (This may actually be the simplest of all the ideas here. The main downside I see is that multiple translations for the same string are apart in the file, possibly causing authors to more easily lose "sync" between them - i.e. `<info lang="en">` suddenly has different regions than `<info lang="de">`.)

I hadn't thought of this idea! That downside exists but info sections should normally be short enough that it wouldn't be a real problem—I mean, if they're long, it'll blow out the summary in Debatekeeper, so I hope authors keep them short 😉

Before I saw that idea, as I was thinking about this overnight, I was thinking of changing all human-readable strings to accepting _either_ a plain string _or_ multiple `<text lang='xx'>` elements, so either of these would be acceptable:

``` xml
  <name>British Parliamentary</name>
```

``` xml
  <name>
    <text lang="en">British Parliamentary</text>
    <text lang="es">Parlamentario Británico</text>
  </name>
```

But this would be invalid:
``` xml
  <!-- invalid -->
  <name>
    British Parliamentary
    <text lang="es">Parlamentario Británico</text>
  </name>
```

The schema can be set up to enforce this fairly easily, I think. (It can also enforce adjacency.) Pro: Zero overhead for monolingual formats. Cons: Monolingual and multilingual formats look different from each other; probably complicates handling in the app; backwards-incompatible.

I guess I feel like it depends too much on how multilingual formats end up being used in practice, so I'm probably comfortable with a least-changes-possible approach for now, and if some future developer (hopefully not me lol) has to do a backwards-incompatible overhaul later, I can probably live with that. I confess I'm grasping in the dark a little here—I'm only an aspiring multilingual, and certainly haven't debated in any language other than English.

I'll have a crack at it in a new branch/PR:
- Will try the `<name lang="de">...</name>` and `<info lang="de">...</info>` option. Should be backwards-compatible, since the old code just takes the first element it finds.
- Specifying native language can't be done in `<info>` if multiple `<info lang="es">` elements are allowed, so I'll add a new element at the second level.
- For `DebateFormatFieldExtractor`, I think I'll require adjacency in the schema. Could be unduly restrictive, but not practically difficult, and can be enforced in the new repo by validation and/or post-processing.

-----------------

I realize the irony in the following given that I'm getting to this 3½ after submission, but there's a slight practical deadline—the door closes on apps targeting Android 10 on 1 November 2021, and because of [changes in Android to external storage access](https://github.com/czlee/debatekeeper/wiki/Custom-format-changes-in-version-1.3#why-the-change) I have to target Android 10 with at least one version as a transition! 😂 So—if you're free to chip into discussions, that'd be amazing (no pressure!), and I'm happy to do the dev work, starting with where you left off. (I'm in between jobs, so taking the opportunity now to get this out of the way!) Thanks again!

**Comment by res2k** [comment]
> I think we have good reason to consider the reasons offered there not to apply to our case—format files are short and will probably often be "localized" by their authors. Well, at least that's true if we expect most formats to be published only in their native language and maybe one or two others. I suppose I could imagine a system where debate formats are localized like how most software is, but… there's a Pandora's box opened once we go there.

In addition, I suspect a lot of the terms in a debating format are set and thus unlikely to change, meaning translations aren't that likely to go stale either.

> I guess I feel like it depends too much on how multilingual formats end up being used in practice, so I'm probably comfortable with a least-changes-possible approach for now, and if some future developer (hopefully not me lol) has to do a backwards-incompatible overhaul later, I can probably live with that. I confess I'm grasping in the dark a little here—I'm only an aspiring multilingual, and certainly haven't debated in any language other than English.

My guesses are:
* Formats that are used primarily in one region (similar to OPD now) might be written in their "native" language first, with possibly English added, as it may benefit speakers whose first language is not that of the format.
* Formats used the world over (like BP) may receive a number of translations over the time, as non-English speakers will probably use it for debating in their native language. (E.g. I certainly debated BP in German.)

> * Specifying native language can't be done in `<info>` if multiple `<info lang="es">` elements are allowed, so I'll add a new element at the second level.

Right, I didn't think of that.

> I realize the irony in the following given that I'm getting to this 3½ years after submission, but there's a slight practical deadline—the door closes on apps targeting Android 10 on 1 November 2021, and because of [changes in Android to external storage access](https://github.com/czlee/debatekeeper/wiki/Custom-format-changes-in-version-1.3#why-the-change) I have to target Android 10 with at least one version as a transition! 😂 So—if you're free to chip into discussions, that'd be amazing (no pressure!), and I'm happy to do the dev work, starting with where you left off. (I'm in between jobs, so taking the opportunity now to get this out of the way!) Thanks again!

Well, I don't mind the time gap, I'm happy you have some time to look into it now.

**Pull request merged**
